# Generated by Django 2.2.7 on 2019-12-02 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilytreePerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.CharField(blank=True, default='', max_length=10)),
                ('birth_place', models.CharField(blank=True, default='', max_length=50)),
                ('status_choices', models.CharField(choices=[('living', 'living'), ('deceased', 'deceased'), ('unknown', 'unknown')], default='living', max_length=35)),
                ('sex_choices', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default='other', max_length=35)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FamilytreeRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationships', models.CharField(choices=[('father', 'father'), ('mother', 'mother'), ('brother', 'brother'), ('sister', 'sister'), ('son', 'son'), ('daughter', 'daughter'), ('adoptive son', 'adoptive son'), ('adoptive daughter', 'adoptive daughter'), ('surrogate father', 'surrogate father'), ('surrogate mother', 'surrogate mother'), ('stepbrother', 'stepbrother'), ('stepsister', 'stepsister'), ('stepdaughter', 'stepdaughter'), ('stepson', 'stepson')], default='father', max_length=35)),
                ('id_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_1', to='familytree.FamilytreePerson')),
                ('id_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_2', to='familytree.FamilytreePerson')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
