# Generated by Django 2.2.7 on 2019-12-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familytreeperson',
            name='avatar',
            field=models.CharField(default='/media/avatars/0.png', max_length=200),
        ),
    ]
