# Generated by Django 2.2.7 on 2019-11-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0002_auto_20191125_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familytree',
            name='relationship',
            field=models.ManyToManyField(blank=True, to='familytree.FamilytreeRelationship'),
        ),
    ]
