# Generated by Django 2.2.6 on 2019-10-12 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0003_familytreeperson_status_of_life'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familytreeperson',
            old_name='status_of_life',
            new_name='status_choices',
        ),
    ]
