# Generated by Django 2.2.7 on 2019-11-25 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0003_auto_20191125_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familytreerelationship',
            name='id_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_1', to='familytree.FamilytreePerson'),
        ),
        migrations.AlterField(
            model_name='familytreerelationship',
            name='id_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_2', to='familytree.FamilytreePerson'),
        ),
    ]
