# Generated by Django 2.2.6 on 2019-10-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0004_auto_20191012_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familytreeperson',
            name='status_choices',
            field=models.CharField(choices=[('Living', 'Living'), ('Deceased', 'Deceased'), ('Unknown', 'Unknown')], default='Living', max_length=2),
        ),
    ]
