# Generated by Django 2.2.6 on 2019-10-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0005_auto_20191012_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familytreeperson',
            name='status_choices',
            field=models.CharField(choices=[('Living', 'living'), ('Deceased', 'deceased'), ('Unknown', 'unknown')], default='Living', max_length=2),
        ),
    ]
