# Generated by Django 2.2.6 on 2019-10-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0007_auto_20191014_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='familytreeperson',
            name='sex_choices',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default='other', max_length=2),
        ),
    ]
