# Generated by Django 2.2.6 on 2019-10-14 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0009_familytreeperson_birthplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familytreeperson',
            name='birthplace',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
