# Generated by Django 2.2.6 on 2019-10-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0011_auto_20191015_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familytreeperson',
            name='birth_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='familytreeperson',
            name='birth_place',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
