# Generated by Django 2.2.6 on 2019-10-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0012_auto_20191015_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familytreeperson',
            name='birth_date',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='familytreeperson',
            name='birth_place',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
