# Generated by Django 2.2.6 on 2019-10-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0013_auto_20191015_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilytreeRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_1', models.CharField(max_length=50)),
                ('id_2', models.CharField(max_length=50)),
                ('relationships', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default='other', max_length=2)),
            ],
        ),
    ]
