# Generated by Django 2.2.6 on 2019-10-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0014_familytreerelationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familytreerelationship',
            name='relationships',
            field=models.CharField(choices=[('father', 'father'), ('mother', 'mother'), ('brother/sister', 'brother/sister')], default='father', max_length=2),
        ),
    ]
