# Generated by Django 2.2.6 on 2019-11-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0016_auto_20191022_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='familytreeperson',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='familytreeperson',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
