# Generated by Django 2.2.6 on 2019-11-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0017_auto_20191111_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familytreeperson',
            name='status_choices',
            field=models.CharField(choices=[('living', 'living'), ('deceased', 'deceased'), ('unknown', 'unknown')], default='living', max_length=35),
        ),
    ]
