# Generated by Django 2.2.7 on 2019-11-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0018_auto_20191111_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familytreeperson',
            name='x',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='familytreeperson',
            name='y',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='familytreerelationship',
            name='relationships',
            field=models.CharField(choices=[('father', 'father'), ('mother', 'mother'), ('brother', 'brother'), ('sister', 'sister'), ('son', 'son'), ('daughter', 'daughter'), ('adoptive son', 'adoptive son'), ('adoptive daughter', 'adoptive daughter'), ('surrogate father', 'surrogate father'), ('surrogate mother', 'surrogate mother'), ('stepbrother', 'stepbrother'), ('stepsister', 'stepsister'), ('stepdaughter', 'stepdaughter'), ('stepson', 'stepson')], default='father', max_length=35),
        ),
    ]
