// File which contains enum types

export enum NOTIFY {
    SUCCESS_LOGIN,
    SUCCESS_REGISTER,
    SUCCESS_LOGOUT,

    ERROR,
    ERROR_LOGIN,
    ERROR_TIMEOUT,

    RESET,

    SAVE_PERSON,
    SAVE_RELATIONSHIP,
    SAVE_COORDS,
    SAVE_MILESTONE,
    SAVING,

    ADD_PERSON,
    ADD_RELATIONSHIP,
    ADD_MILESTONE,

    DELETE,
    DELETE_PERSON,
    DELETE_RELATIONSHIP,
    DELETE_MILESTONE,
}

export default NOTIFY;