# Generated by Django 3.0.2 on 2020-01-25 14:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilytreePerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_date', models.CharField(blank=True, default='', max_length=10)),
                ('birth_place', models.CharField(blank=True, default='', max_length=50)),
                ('avatar', models.ImageField(upload_to='avatars')),
                ('status_choices', models.CharField(choices=[('living', 'living'), ('deceased', 'deceased'), ('unknown', 'unknown')], default='living', max_length=35)),
                ('sex_choices', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default='other', max_length=35)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FamilytreeRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='#ffffff', max_length=7)),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=512)),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField(blank=True, default=None, null=True)),
                ('descendant', models.BooleanField(default=False)),
                ('relationships', models.CharField(choices=[('married', 'married'), ('divorced', 'divorced'), ('fiance', 'fiance'), ('sibling', 'sibling'), ('stepsibling', 'stepsibling'), ('sibling-in-law', 'sibling-in-law'), ('cousin', 'cousin'), ('niece/nephew', 'niece/nephew'), ('child', 'child'), ('adopted child', 'adopted child')], default='married', max_length=35)),
                ('id_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_1', to='familytree.FamilytreePerson')),
                ('id_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_2', to='familytree.FamilytreePerson')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FamilytreeMilestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('text', models.CharField(blank=True, max_length=512)),
                ('title', models.CharField(max_length=64)),
                ('image', models.FileField(upload_to='milestones', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'bmp', 'svg', 'raw', 'mp4', 'webm', 'wmv', 'avi', 'wav', 'mp3'])])),
                ('person_id', models.ManyToManyField(to='familytree.FamilytreePerson')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
