# Generated by Django 3.1.6 on 2024-11-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familytreerelationship',
            name='begin_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='familytreerelationship',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
