# Generated by Django 3.1.6 on 2024-12-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familytree', '0002_auto_20241121_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='familytreeperson',
            name='death_date',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
